name: Docker Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: joydeep2022/reactjs-shopcart:${{ github.run_number }}

  deploy-remote:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
           ssh-keygen -t rsa
           ssh-copy-id ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
           ssh-keyscan -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
           chmod 644 ~/.ssh/known_hosts

      - name: Connect to remote machine and execute command
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cat /home/milindsurya34/reactshop/reactshop/Dockerfile'
